### ISSUE TITLE
Main Page 구현

### ISSUE THREAD

**Issue by silverstone2** [silverstone2/TODAYS#2]
2022-12-14 
1. 모든 페이지 상단에 고정으로 표시될 navbar 구현
2. main_page - 날씨 정보, 추천 카페 목록 보기 등 기본 frame 구현 ( 기상청 API 활용 )

**Comment by Sayh0** [comment]
2022-12-15
1. checkin.html 생성하여 최초에 브라우저에서 사용자 위치 정보 수집 승인 요청 기능 구현
2. 이후 응답받은 위치정보(위도, 경도) 서버로 전달하여 기상청 API와 연동 구현 중

**Comment by silverstone2** [comment]
2022-12-16
1. 사용자 위치 정보 수집 요청 승인 후 위도, 경도 정보를 서버로 전달하여 기상청 API 연동 구현 완료
    (  json decode 관련 문제 해결(SERVICE_KEY_VALUE_ERROR)을 위해 merge 진행 X )

**Comment by silverstone2** [comment]
2022-12-17
1. 추천 카페 관련 버튼 클릭 시 스크롤 이동
2. 카페 목록 리스트 표시
3. 2022-12-16 json decode 관련 문제 해결 완료 ( merge 진행 )

**Comment by silverstone2** [comment]
2022-12-19
1. 웹페이지 연결 구조 변경
2. 카페 조건 검색 시 result.html로 이동하여 검색한 내용에 대한 결과를 보여줌

**Comment by silverstone2** [comment]
2022-12-22
1. 사용자 지역 선택 기능 구현
2. 카페 카테고리 선택 기능 구현
