### ISSUE TITLE
기능 함수 functions.py로 이동 요청

### ISSUE THREAD

**Issue by Sayh0** [silverstone2/TODAYS#6]
2022-12-19

select_location branch에서 수정된 코드 확인 가능합니다.

1. 선택한 지역을 좌표로 변환하는 r_geocoder 함수 생성 (fucntions.py 파일)
2. 기능함수들 모두 functions.py 로 이동
3. views.py 에는 request 받은 값 templates 로 전달하는 함수만 남김.

--작성자 윤성훈--

**Comment by silverstone2** [comment]
해당 function 외 다수 function을 functions.py파일로 이동 완료
